DROP TABLE Categories CASCADE;
DROP TABLE Customers CASCADE;
DROP TABLE Employees CASCADE;
DROP TABLE Shippers CASCADE;
DROP TABLE Suppliers CASCADE;
DROP TABLE Products CASCADE;
DROP TABLE Orders CASCADE;
DROP TABLE OrderDetails CASCADE;